---
- name: Exercise4
  hosts: arista

  tasks:
    - name: Retrieve the switching table as JSON
      eos_command:
        commands: show mac address-table | json
      register: output
   
    - name: Retrieve unicast switching table from data structure
      set_fact:
        switch_table: "{{ output.stdout[0].unicastTable.tableEntries }}"

    - debug:
        msg: "{{ item }}"
      loop: "{{ switch_table }}"

    - set_fact:
        switch_table_list: "{{ switch_table_list | default([]) + [item.macAddress] }}"
      loop: "{{ switch_table }}"

    - debug:
        var: switch_table_list 
